# Generated by Django 4.0.1 on 2022-01-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0002_remove_user_firstname_remove_user_id_code_and_more'),
        ('login_signup', '0002_rename_job_doctor_job_id_rename_rpps_doctor_rpps_id_and_more'),
    ]

    operations = [
    ]
