# Generated by Django 4.0.1 on 2022-01-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0004_alter_appointment_user_id_alter_doctor_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
