# Generated by Django 4.0.1 on 2022-01-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0005_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(max_length=100),
        ),
    ]
