# Generated by Django 4.0.1 on 2022-01-31 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0007_alter_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diseases',
            field=models.ManyToManyField(related_name='User_disease', through='login_signup.UserDisease', to='login_signup.Diseases'),
        ),
        migrations.AlterField(
            model_name='userdisease',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_signup.user'),
        ),
    ]
