# Generated by Django 4.0.1 on 2022-01-31 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_signup', '0009_rename_job_id_doctor_job_rename_rpps_id_doctor_rpps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='diseases',
            field=models.ManyToManyField(null=True, related_name='User_disease', through='login_signup.UserDisease', to='login_signup.Diseases'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userKey', to=settings.AUTH_USER_MODEL),
        ),
    ]
